package crm;

import java.awt.Dimension;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author kexital
 */
public class AScrollList extends JScrollPane {

//    needed for def constructor. Because when panel
//    appears it must already show somethig to prevent user to be puzzled
//    with empty list. Panel should show something. In this case Contacts of
//    the first firm in firm list.

// TODO condition: firmList must chose first firm record to anable this featre
   
    private String firmContacts[];      
    private int recPerFirm;
    
    public JButton unnecessaryDemoButton2= new JButton("lists1");
    public JButton unnecessaryDemoButton1= new JButton("lists2");
    private ContactCard contactCard = new ContactCard();
    
    public JPanel panel;
    public GroupLayout layout;
    /**
     * Creates new JPanel that represents Scrollable contacts list
     */
    public AScrollList (){
        paint();
    }
    public AScrollList(String firmContact[], int recPerFirm) {
        paint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void paint() {

        panel = new javax.swing.JPanel();
        layout = new GroupLayout(panel);
        
        panel.setLayout(layout);
       
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(contactCard)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contactCard)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        this.setViewportView(panel);
        this.setSize(new Dimension(800,800)); 
        }
    // </editor-fold>
    
   
    
    
}
